### ISSUE TITLE
Please review problem statement.

### ISSUE THREAD

**Issue by Malavika-Srinivasan** [Malavika-Srinivasan/CAS741#1]
@smiths 

Hello Dr.Smith,

Thank you for the extension. Please see my problem statement - 96fe9b1 and let me know your suggestions.

Thank you,

Malavika

**Comment by Malavika-Srinivasan** [comment]
@smiths ,


Hello Dr.Smith,


I made the changes in problem statement as per your suggestion on Sep 17, 2018. I still have one more question and I wrote it in the document. Can you please review it?

1debb46

Thank you,
Malavika

**Comment by smiths** [comment]
Question is addressed in b597201.

**Comment by smiths** [comment]
Please address the comments in the problem statement so that we can close this issue.

**Comment by Malavika-Srinivasan** [comment]
@smiths ,


Hello Dr.Smith,

I addressed the comments in the problem statement. Please review it.
1e2cf30

Regards.


Malavika

**Comment by smiths** [comment]
I made some edits to the problem statement in 4a6c932bf3d08ab1b92fc8ea9bc843aa48764090.  Mainly it is some wording changes and changing the textwidth in the tex file to 80 columns.  In commit 8deeff0, I added .DS_Store to the .gitignore file.

**Comment by Malavika-Srinivasan** [comment]
Thank you @smiths . I will make sure I don't forget the column spacing.
