### ISSUE TITLE
[SystVnVPlan Review] Typos and Comments About Document Formatting

### ISSUE THREAD

**Issue by hananezlitni** [Malavika-Srinivasan/CAS741#17]
Below are comments about typos and document formatting:

**Introduction (paragraph above Section 3)**
- For better readability, it would be better to put the "ISO" reference after "portability" at the end of line 6 between brackets.

- I believe that the first letter of each characteristic listed in this section should not be capitalized (e.g. "... set of characteristics namely - functional suitability, performance, efficiency, ..."). This is similar to other sections in this document unless the characteristic is a title/subtitle.

**Section 3.1**
- In line 2, I believe it's "in compliance with" instead of "for compliance with".

- In line 3, “as found in the CA” instead of “as found in CA”. This is the same in other sections in the document.

- Capitalize the first letter of “compute” in the goal statement

**Section 3.2**
- In line 1, it says "the goal of verifying and validating is to..." . For better grammar, I suggest saying “The goal of the verification and validation plan...” or “the goal of verifying and validating CFS...”

- There's a typo in line 1 in "... is to increase improve the quality of..." (either "increase the quality of" or "improve the quality of")

**Section 5**
- In line 1, I believe there’s a missing word in the sentence “System testing is a process in which only the overall working of the system.” .. you may make it "System testing is a process in which we test the overall working of the system.", for example.

**Section 5.1**
- There are inconsistencies in the capitalization of the first letters of “Test case reference” in some test case (in some test cases the second and third words are all small and in others "reference" is capitalized).. "case" and "reference" should be in small letters for all test cases.

**Comment by Malavika-Srinivasan** [comment]
Hi @hananezlitni ,


Thank you so much. 
Closing this issue, changes made in fae7b1e
