### ISSUE TITLE
[SystVnVPlan Review] Introduction

### ISSUE THREAD

**Issue by hananezlitni** [Malavika-Srinivasan/CAS741#18]
**In the introduction (above section 3):**

- I believe it would be better to provide a description of the document content (mention what each section talks about)

- I think that the paragraph “There are several standards …” (line 2) till the end is more appropriate in the “objectives” section (where you define the qualities/characteristics), because when I read it, it sounded too specific and the introduction should be abstract.

**Comment by Malavika-Srinivasan** [comment]
Thanks @hananezlitni. Closing this issue.


6352b25

**Comment by Malavika-Srinivasan** [comment]
44299db - Latest edit in regards to this issue
