### ISSUE TITLE
[SystVnVPlan Review] Tests for Functional Requirements

### ISSUE THREAD

**Issue by hananezlitni** [Malavika-Srinivasan/CAS741#19]
**In section 5.1 (Tests for Functional Requirements):**

- For the test cases in which the outputs are error messages, you could add “or corresponding/related exception”. Dr. Smith suggested this to me during my presentation and it’s a good suggestion to avoid comparing strings.

- For better clarity, and to have descriptive titles, I suggest modifying the titles for 5.1.1 in this way:
    - 5.1.1 Test cases for faulty inputs
        1. T1: Test case for inputs with less than 2 points
        2. T2: Test case for data type mismatch

- Is the statement (Coefficients of t, starting from…) part of the output? If not, it might be better to either write that as a note after each test case (not next to "output"), or somewhere else where you see appropriate. If it is part of the output, you can disregard my comment. It got me a little confused as there are some test cases that don’t have this statement next to the output.

- For the test case references where the reference is a link, I believe that you should put the link at the end of the document and use cross-referencing in the plainnat convention (the references in this case would be of type "url").

- Are the inputs “t” and “y” in all test cases data points? It is mentioned in some test cases in "input" and not in others.. if they are data points you should right that in all the test cases.

**Comment by Malavika-Srinivasan** [comment]
@hananezlitni 


Hi Hanane,

Please see my answer below.

1. I plan to have, Coeff of t as part of my output so that the user knows how to construct the polynomial back.
2. Remaining changes made.

Thank you for the feedback.

**Comment by hananezlitni** [comment]
@Malavika-Srinivasan sounds good (:

**Comment by Malavika-Srinivasan** [comment]
closing this issue as all the changes have been made.
