### ISSUE TITLE
Add a .gitignore file

### ISSUE THREAD

**Issue by smiths** [Malavika-Srinivasan/CAS741#2]

**Comment by smiths** [comment]
Please address the comments in 6045226.

**Comment by Malavika-Srinivasan** [comment]
Added a git ignore file. So, closing this issue.

**Comment by smiths** [comment]
You were supposed to add a .gitignore file, not a gitignore.txt file.  I don't think git will find your txt file.  Did you test it?  When closing an issue, please give me the commit number that addresses the request.  It makes it easier to check.

**Comment by Malavika-Srinivasan** [comment]
@smiths 
Hello Dr.Smith,
I added a gitignore file and removed gitignore.txt. - 82165389a2e29e295a6229d7a001670d5ffbad54
Thank you,
Malavika

**Comment by smiths** [comment]
Great!
