### ISSUE TITLE
[SystVnVPlan Review] Tests for Nonfunctional Requirements

### ISSUE THREAD

**Issue by hananezlitni** [Malavika-Srinivasan/CAS741#20]
**In Section 5.2 (Tests for Nonfunctional Requirements):**
- For T20, since you’re comparing with Matlab, I believe the type should be “parallel testing”.

- In T20, I think it’s better to mention that the “admissible error” is defined in the appendix, using by cross-referencing.

- For T21, I believe you should elaborate in “how test will be performed” and explain what exactly the test consists of. I personally didn't really understand the steps.

**Comment by Malavika-Srinivasan** [comment]
For T20, I added parallel testing along with manual and non functional. I always had the thought that type refers to either manual or automatic. But adding parallel testing also makes sense :)

All the changes have been made, closing this issue.

**Comment by Malavika-Srinivasan** [comment]
d13e009
