### ISSUE TITLE
[SystVnVPlan Review] Minor Comments/Suggestions

### ISSUE THREAD

**Issue by hananezlitni** [Malavika-Srinivasan/CAS741#21]
**Minor comments/suggestions**
- It would be better to link your project documentation on GitHub in the introduction.

- You could add your CA in the references at the end of the document and use cross-referencing where appropriate.

- The "References" section at the end of the document is repeated twice (in pages 12 and 13).

This is the last issue. You have done a good job with the document (:

**Comment by Malavika-Srinivasan** [comment]
@hananezlitni,

Thank you so much for the feedback. It was very useful and I appreciate it.

**Comment by hananezlitni** [comment]
@Malavika-Srinivasan you're welcome (:
