### ISSUE TITLE
Please review MG

### ISSUE THREAD

**Issue by Malavika-Srinivasan** [Malavika-Srinivasan/CAS741#23]
@smiths 

Hello Dr.Smith,

Please review my MG.

https://github.com/Malavika-Srinivasan/CAS741/tree/master/docs/Design/MG

Thank you,
Malavika

**Comment by smiths** [comment]
Thank you.

**Comment by Malavika-Srinivasan** [comment]
Since my MG has been reviewed, I am closing this issue.
