### ISSUE TITLE
MG anticipated changes (AC) questions

### ISSUE THREAD

**Issue by PeaWagon** [Malavika-Srinivasan/CAS741#26]
AC4 - unsure who "they" refers to. Perhaps better to write "the user" as in UC5. 

Do you have an idea for a specific change for AC2, similar to the specific cases given in AC's 3 and 4? Can you consolidate AC5 with AC2? I'm not sure AC5 counts as input format (since AC5 seems to be adding a new feature to your library). 

For AC3, does smoothing perform better than interpolation and regression? Is there a reason you are replacing the calculations with smoothing? Would it make more sense to have an extra option so the user can decide which method to use for their data set?

**Comment by Malavika-Srinivasan** [comment]
Thanks Jen. @PeaWagon 

I made some changes to the document. I don't discuss about smoothing anymore and don't have variabilities in input format. 

Malavika
