### ISSUE TITLE
MG question for section 6 module decomp.

### ISSUE THREAD

**Issue by PeaWagon** [Malavika-Srinivasan/CAS741#27]
For the plot module, is it sufficient to say that Python will implement the plotting of the data? Does this mean that Python can plot data without an external library, or will you use an external library (e.g. Matplotlib)? Same for sequence services module? Since Python uses lists by default, would you be using Numpy in this case?

**Comment by Malavika-Srinivasan** [comment]
Mentioned matplotlib and numpy explicitly. Thanks @PeaWagon .


Malavika
