### ISSUE TITLE
couple of small points

### ISSUE THREAD

**Issue by PeaWagon** [Malavika-Srinivasan/CAS741#28]
- subject-verb agreement
UC3 "then the results from the software **are**" (replaces **is**)

- For Table 1, change the multirow to 4 to centre software decision module in the middle.
\multirow{3}{0.3\textwidth}{Software Decision Module} & Sequence Services\\
& Interpolation\\
& Linear Regression\\
& Plot\\
\bottomrule

- inconsistent sentence ending ('.' versus no dot) for module services sections

**Comment by Malavika-Srinivasan** [comment]
Thanks all changes made.
