### ISSUE TITLE
MIS issues

### ISSUE THREAD

**Issue by Malavika-Srinivasan** [Malavika-Srinivasan/CAS741#29]
1. Syntax
2. Dr.Smith to Dr.\_Smith(in latex) or Dr.~Smith [Suggestions for correct spacing] 
~ means no line break
3. Spell check and proof read
4. Take out ``Static verification Technique '' to a different section
5. Refer slide 8/43 in Lecture 18 for important administrative feedback
6. For MIS review: refer 11/43 in lecture 18. They act as checklist for reviewing MIS.
7. External envt -  A module can cause change of state in another module. That will be a state transition. If we read input from file, file is in envt and for plots, plots is outside the program which is in the envt. Think about how it will interact with the external envt. For eg: to open a door, its not enough if we just write doorOPEN = True. We need an envtl variable to deal with external world.
8. Look at examples - PCM
9.

**Comment by smiths** [comment]
Nice summary.  😄

**Comment by Malavika-Srinivasan** [comment]
@smiths 

Thank you :)

**Comment by Malavika-Srinivasan** [comment]
1. For interpolation module, you don't need a state variable because you already have a output.  So, remove interp.x altogether.

2. Vacuous - Refer to Heath1997 to make sure how he defines vacuous.
3. interpolation and regression don't need to use output module. My user program can use output module.

**Comment by Malavika-Srinivasan** [comment]
Define what is n, when you use them in access programs that n is the size of the array

**Comment by Malavika-Srinivasan** [comment]
N should say R in input module when specifying rules for verification for a non number input

**Comment by Malavika-Srinivasan** [comment]
Try and use the same name as in SRS.

**Comment by Malavika-Srinivasan** [comment]
Closing this issue.
