### ISSUE TITLE
Question about details for CA

### ISSUE THREAD

**Issue by Malavika-Srinivasan** [Malavika-Srinivasan/CAS741#3]
@smiths 

Dr.Smith,

I am classifying my software as shown below. 

Interpolation

1. Polynomial
2. Piecewise
3. Trignometric
4. exponential
5. Rational 

Polynomial has subtypes and Piecewise has subtypes too (Which will be about 8 to 9 IM for interpolation).

In the textbook, they discuss only about Polynomial and Piecewise. Should we stop at that point or continue with other types too? Please clarify.

Thank you,

Malavika

**Comment by smiths** [comment]
@Malavika-Srinivasan, you can stop at polynomial and piecewise.  Trigonometric is usually done use fast Fourier transforms, which would be another projects worth of information.  Be sure to delineate your scope in the scope section.

**Comment by Malavika-Srinivasan** [comment]
Thank you Dr.Smith. I am closing this issue.
