### ISSUE TITLE
MIS - Issues with Environment Variables

### ISSUE THREAD

**Issue by bmaclach** [Malavika-Srinivasan/CAS741#37]
I have a few comments about the environment variables you've used in your MIS:

- In section 6.4.2, you specify the type of inputFile as "sequence of string". This is minor, but I think it is okay to just say "string" as the type to be more concise. 
- In section 9.4.2, you've declared the type of OutputFile as "Results.csv", but I think it should also be a string. "Results.csv" is the name of the file, which maybe you can include as part of an additional description about what OutputFile represents (see next point)
- In both sections 6.4.2 and 9.4.2, I think it would be helpful to have more information about the variable. You could add an additional sentence saying inputFile represents a file in the hardware's file system (and similarly for OutputFile)
- In section 9, you define the environment variable OutputFile but you never reference it in the specification. I think you should reference it in the specification for the coeffFile method.

**Comment by smiths** [comment]
@bmaclach - thank you for the detailed comments.  One comment I would like to reinforce is that sequence of string means something different than string.  A sequence of characters is a string, a sequence of string is a sequence of sequences of characters.  😄

**Comment by bmaclach** [comment]
@smiths Right. But a file can be modeled just as a string, right? My comment was aimed at simplifying the type, as I didn't see the need for the more complicated "sequence of string" type. Although thinking about it now, I can see why it might be useful to think of a file as a sequence of strings (one for the file name and one for the file contents), so it might be better to leave it as is.

**Comment by smiths** [comment]
@bmaclach, yes a file can be modelled as a string.  The choice of type to use for modelling the file depends on how it will be used.  If you need to easily reference the individual strings (words) in the file, a sequence of strings would make sense.  However, I don't think we are talking about something like this.  Viewing the file as a sequence of characters (which will include newline characters) is fine.

**Comment by Malavika-Srinivasan** [comment]
I made the changes discussed above. Closing this issue.
