### ISSUE TITLE
MIS - Question about degVerify

### ISSUE THREAD

**Issue by bmaclach** [Malavika-Srinivasan/CAS741#38]
In the Input module you have a state variable called degVerify which is a boolean for whether the degree has been verified. However, there are no cases where degVerify is set to false. From what I can tell, it is either set to true, or an exception is thrown. Thus, if an exception is not thrown, then you can safely assume that the degree has been verified. So is it necessary to have that variable at all?

**Comment by Malavika-Srinivasan** [comment]
@bmaclach 

You are right. I can remove the state variable and just return the boolean value. Thanks, I appreciate your detailed feedback.

 - c1f0a76 

Malavika.
