### ISSUE TITLE
MIS - Use of .append in specifications

### ISSUE THREAD

**Issue by bmaclach** [Malavika-Srinivasan/CAS741#39]
All of your "eval" methods use a method called .append, but I could not find a definition for .append anywhere. If it is just appending an element to a list, you can use the concatenation operator from Hoffman and Strooper's notation. So "yNew.append(y<sub>0</sub>)" would become "yNew || y<sub>0</sub>". I also think you should initialize yNew as an empty list, otherwise it is not clear what yNew starts as before appending.

The calls to append all happen after a quantifier for a variable _t<sub>i</sub>_, but _t<sub>i</sub>_ is not always used in the subsequent expressions, so I'm not sure what these specifications mean.

**Comment by Malavika-Srinivasan** [comment]
@bmaclach @smiths ,
Yes, I tried searching for a formal definition for append, but couldn't find any. Maybe I can write array a[i] = x and i = i+1, not sure. 

`||' is for strings right? Thats why I am a little hesitant to use it. 

Dr.smith,

Do you have a suggestion for this?  

Please note, I haven't made changes for this issue yet.

**Comment by bmaclach** [comment]
@Malavika-Srinivasan According to Hoffman and Strooper, the || operator works on any sequence, not just strings, so I think it should be okay to use it here.

**Comment by smiths** [comment]
@bmaclach is correct.  The H&S notation is for any sequence.

**Comment by Malavika-Srinivasan** [comment]
Changed append to ||
