### ISSUE TITLE
MIS - Use of logical or

### ISSUE THREAD

**Issue by bmaclach** [Malavika-Srinivasan/CAS741#40]
Sometimes in the MIS the logical or symbol, \lor, is used on non-boolean values. As an example, in section 9.4.4 the transitions and outputs use the logical or, such as "_out_ := _interp.x_ \lor _reg.x_". The logical or is an operator on booleans, so this implies that _interp.x_, _reg.x_, and _out_ are all boolean values, which I don't think is what you meant.

In cases like these, I would suggest replacing the logical or with a plain word "or". Alternatively, if you want to keep the formal specification, you can probably express this with some conditional rules. It's not clear to me how exactly this would look. You would probably need a variable to represent the choice of solution method, and then write cases based on the value of that variable.

**Comment by Malavika-Srinivasan** [comment]
@bmaclach 
Makes sense. I changed lor to or. 
 - e2c5c20
Thanks,
Malavika

**Comment by Malavika-Srinivasan** [comment]
It is not possible to have a choice because user will be using only one of them at a time. So, in execution this shouldn't be a problem. However, I can see that it is not formal after I replace \lor with or. But I think, its better to keep it simple.
