### ISSUE TITLE
MIS - Plot and Sequence modules

### ISSUE THREAD

**Issue by bmaclach** [Malavika-Srinivasan/CAS741#41]
For completeness of the MIS, you may want to consider adding sections for the Plot and Sequence Services modules. Since these are external to your software, I don't think you should go into detail about how they work, but very simple specifications of their interfaces would be helpful. Also, all of your modules probably use the Sequence Services, so then you could include that module in the Uses subsection for each module.

**Comment by Malavika-Srinivasan** [comment]
@bmaclach 
Added Plot and Sequence modules. Thanks.


Malavika

**Comment by Malavika-Srinivasan** [comment]
oops forgot - 106dbf9 :)
