### ISSUE TITLE
[UnitVnVPlan Review] Table of symbols, acronyms and abbreviations

### ISSUE THREAD

**Issue by hananezlitni** [Malavika-Srinivasan/CAS741#43]
Hi Malavika,

Brooks first pointed this out to me when he gave me comments for my SystemVnVPlan, so I thought I’d do the same for you since you did what I have done back then. 

The acronym “T” is used for “Test” in this document and “Theoretical Model” in the CA. Since you referenced the CA in this section, there may be some ambiguity in this acronym. Brooks back then suggested to either add a small explanation to clarify this or change the acronym. What I did was to remove the reference to the CA and just add the acronyms/symbols/abbreviations used in this document manually.

**Comment by Malavika-Srinivasan** [comment]
@hananezlitni 

Hi Hanane,

I added a small explanation saying that T means Test in this document unlike Theoretical model in CA. I hope it resolves the ambiguity.


Thanks,

Malavika
