### ISSUE TITLE
[UnitVnVPlan Review] Question about T4

### ISSUE THREAD

**Issue by hananezlitni** [Malavika-Srinivasan/CAS741#45]
In test case T4 (verify degree), the exception message says that the degree cannot be a real number. Do you mean it cannot be a decimal? When I think of a degree, for example 45deg, 45 is considered a real number, right? Correct me if I’m wrong.

**Comment by Malavika-Srinivasan** [comment]
@hananezlitni 

The degree refers to the order of the polynomial. So, it cannot be a decimal number. 

45 is a natural number or a positive integer. But 45.0 will be a real number. Also, I could see the ambiguity in the error message, so I changed it to degree must be a natural number.
