### ISSUE TITLE
[UnitVnVPlan Review] Input Module Test Cases

### ISSUE THREAD

**Issue by hananezlitni** [Malavika-Srinivasan/CAS741#46]
There are no test cases that cover the access program loadInput() in this section. If it doesn’t need to be tested, I’d mention that in the paragraph above the test cases.

**Comment by Malavika-Srinivasan** [comment]
@hananezlitni 

Hi Hanane,

I am planning to remove the loadInput() method. So, it is fine. 


Thanks anyway,

Malavika
