### ISSUE TITLE
[UnitVnVPlan Review] Minor comment about traceability table

### ISSUE THREAD

**Issue by hananezlitni** [Malavika-Srinivasan/CAS741#47]
This is a very minor comment, but you used M1-M3 in the traceability table and you didn’t indicate what module each numbering represents. Therefore, I’d add next to “input module”, “interpolation module” and “regression module” subtitles in 5.1.1, 5.1.2 and 5.1.3, respectively, the numbering (M1-M3).

This is my last comment. Good job with the document! (:

**Comment by Malavika-Srinivasan** [comment]
Thanks @hananezlitni . I changed M1 , M2 and M3 to Input, Interpolation and Regression module.


Malavika
