### ISSUE TITLE
Theoretical models before Data definitions

### ISSUE THREAD

**Issue by Malavika-Srinivasan** [Malavika-Srinivasan/CAS741#5]
@smiths 

Hello Dr.Smith,

I had a question with the CA template. In CA, the Data definitions appear before the Theoretical models. I think Theoretical models should appear first. Please confirm. 

Thank you,
Malavika

**Comment by smiths** [comment]
Yes, you can put the data definitions after the theoretical models.

**Comment by Malavika-Srinivasan** [comment]
@smiths 


I am closing this issue. I actually  General definitions -->  Theoretical models --> Data definitions was more appropriate for my case. So, I arranged it accordingly.

@whitere123, #10 is also done.
