### ISSUE TITLE
Please review CA

### ISSUE THREAD

**Issue by Malavika-Srinivasan** [Malavika-Srinivasan/CAS741#6]
@smiths 

Hello Dr.Smith,

Thank you for the deadline extension. I just submitted my CA. Please review and let me know your feedback.
82e048f

Thank you,

Malavika

**Comment by smiths** [comment]
@Malavika-Srinivasan, I look forward to reviewing your document.

**Comment by smiths** [comment]
@Malavika-Srinivasan, I've added some minor comments to your CA (see a4e6688).  The review will continue soon.

**Comment by Malavika-Srinivasan** [comment]
@smiths ,


Hello Dr.Smith,

I made the changes mentioned in your commit( a4e6688). Please see my changes at  5d25403.


Thank you,
Malavika

**Comment by smiths** [comment]
The changes look good.  My complete review is in 4d6d743.
