### ISSUE TITLE
CA review - comment # 2 

### ISSUE THREAD

**Issue by whitere123** [Malavika-Srinivasan/CAS741#8]
This comment is regarding your introduction. 

#2 
- I think that you should make section 3.1 more clear. You could elaborate more on the statements " assumptions which are true" and "assumptions which can vary". It would help if you explicitly wrote what the reader should know after reading this document. 

- Perhaps 3.3 could be a bit more specific. (which courses should they be familiar with? It seems like elementary linear algebra is a strong pre-requisite for this document).

**Comment by Malavika-Srinivasan** [comment]
@whitere123 ,


Hi robert, 

Please see my reply below. 

1. " I think that you should make section 3.1 more clear." - Good idea. I will work on this and tag you for review.

2. Perhaps 3.3 could be a bit more specific. (which courses should they be familiar with? It seems like elementary linear algebra is a strong pre-requisite for this document). - Very useful feedback. I will change it in the document. 

Malavika

**Comment by Malavika-Srinivasan** [comment]
@whitere123 , @smiths 


Closing this issue. Both the changes suggested above are made. - ff5460c
@whitere123 , Thanks for the feedback. 
Malavika
