### ISSUE TITLE
CA Review - Comment #3

### ISSUE THREAD

**Issue by whitere123** [Malavika-Srinivasan/CAS741#9]
This comment is about the user responsibilities. 

#3 
- It may also be the user's responsibility to organize their data into matrix form and/or understand the meaning of the rows and columns with respect to their dataset. 
- You may be able to merge your second and third user responsibilities into one. Maybe something like: "Input whether to use interpolation or regression and decide on corresponding method"

**Comment by Malavika-Srinivasan** [comment]
@whitere123 

Hi Robert,
It may also be the user's responsibility to organize their data into matrix form and/or understand the meaning of the rows and columns with respect to their dataset. - I don't think it is good to ask the user to enter data in matrix form. Besides, if we do that, I may want to change the input everywhere in the document and it will become something like a constraint. So, I am not sure if it is good idea. Bit I will keep this in mind if I have trouble forming matrix from the given set of data points.

You may be able to merge your second and third user responsibilities into one. Maybe something like: "Input whether to use interpolation or regression and decide on corresponding method" - Yes it is a good idea but I prefer to keep them separate as thy are variabilities by themselves and each of them have further variabilities. I think separating them makes referencing a little easier to understand the logical structure.


I will wait for your reply before I close this issue.

**Comment by whitere123** [comment]
By organize their data I meant that they should have a column of ti and a column of yi. The user should understand the role of ti and yi with respect to your software. (ie they want to get y as a function of t at the end of the day, and not get the other way around)

**Comment by Malavika-Srinivasan** [comment]
Ok, then we have the problem solved. I can add this to user responsibilities.
